### ISSUE TITLE
Can't download pools image

### ISSUE THREAD

**Issue by starlight-tu** [moebooru/moebooru#10]
I did sign in to Yande.re but I can't download it.  When I click download, it returns me to log-in page. So I think maybe I should log-in again but it continues return me back to log-in page.
What should I do now? I already deleted cookies, cache.

**Comment by coli** [comment]
Got the same issue at https://yande.re/pool/show/3769 https://yande.re/pool/zip/3769/Eshi%20100-Nin%20Ten%2005.zip

Seems to be file name related?

**Comment by nanaya1** [comment]
incorrect web server configuration. Should be fixed now.
