### ISSUE TITLE
Entering browse mode bug 

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#104]
Problem 1 (pooled posts):

1. Open a post in a pool, such as https://yande.re/post/show/466553
2. Press `B`, it enters browser mode _of that pool_, working as expected. 

However, if you changed to the previous/next page (in normal mode) first, and the URL will become something like https://yande.re/post/show/466555?pool_id=5137
Now, pressing `B` will *not* enter browse mode of that pool, just this single post.

Problem 2:

Similarly, if you enter browser mode from any non-pooled post, it will enter such single post mode as well. For example, go https://yande.re/post/show/466699 and press `B`. I didn't quite remember the previous behavior, but I think it used to be browsing the main index starting from this page.

**Comment by nanaya** [comment]
Should be fixed now.
