### ISSUE TITLE
Manual blacklist recheck

### ISSUE THREAD

**Issue by ghost** [moebooru/moebooru#106]
Is it possible to trigger the blacklist check that runs on init manually calling a function? I'm injecting new posts without loading new pages with inifinite-scroll.js but posts are hidden by default so I'm looking for a manual recheck I can use after each injection

https://github.com/moebooru/moebooru/blob/f46ef831771a012ce537545869dfbb8be8a46293/lib/assets/javascripts/moe-legacy/post.js#L522

**Comment by nanaya** [comment]
You're on your own by adding external script.
