### ISSUE TITLE
Blacklist doesn't work

### ISSUE THREAD

**Issue by zombiemonkey6969** [moebooru/moebooru#111]
I tried blacklisting to_love_ru on yande.re, but pictures with that tag still appear, like when I looked up gym uniform I still saw multiple pictures with the to_love_ru tag, please fix this bug

**Comment by fireattack** [comment]
Cannot reproduce it.

![image](https://user-images.githubusercontent.com/4130991/56998859-77b05780-6b72-11e9-9aa3-d8d1b75e9e26.png)

![image](https://user-images.githubusercontent.com/4130991/56998870-87c83700-6b72-11e9-9dcb-fa9dd7c8d0f9.png)

**Comment by zombiemonkey6969** [comment]
Can't reproduce it, what do you nean? and if the blacklist doesn't work then what's the point of having that setting?

**Comment by nanaya** [comment]
Please provide screenshots of your blacklist setting and where you're seeing it doesn't work.

**Comment by zombiemonkey6969** [comment]
![Capture+_2019-05-01-18-20-50](https://user-images.githubusercontent.com/50156831/57051332-43a26880-6c3e-11e9-9715-c602581cc064.png)
![Capture+_2019-05-01-18-22-21](https://user-images.githubusercontent.com/50156831/57051333-43a26880-6c3e-11e9-8167-de836f82b022.png)
![Capture+_2019-05-01-18-22-29](https://user-images.githubusercontent.com/50156831/57051334-443aff00-6c3e-11e9-8d9b-82fe2f6defe5.png)
![Capture+_2019-05-01-18-22-10](https://user-images.githubusercontent.com/50156831/57051335-443aff00-6c3e-11e9-9f71-680c1595e20e.png)
Ok, here

**Comment by fireattack** [comment]
Each line in blacklist represents a combination of tags that need to match together (`AND`).
If you want to ban multiple tags, put them on different lines.

**Comment by zombiemonkey6969** [comment]
Strange system but ok, thank you! :3
