### ISSUE TITLE
Ban doesn't expire properly

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#112]
It seems sometimes the ban won't be lifted even when the time is up.

Examples:

https://yande.re/user/show/123317
https://yande.re/user/show/12631
https://yande.re/user/show/28620

(There are hundreds of them.)

Not sure if it's a database problem.

**Comment by nanaya** [comment]
I think they're removed on the user's next login.

**Comment by fireattack** [comment]
That explains it. Also I found that visiting user page is *very* for a while, is that normal?

**Comment by nanaya** [comment]
Yeah user page is currently quite slow but I don't really have time to check it (and there are other more pressing problems and no one else seems to be complaining yet).
