### ISSUE TITLE
Questions regarding Moebooru and Danbooru

### ISSUE THREAD

**Issue by DonaldTsang** [moebooru/moebooru#113]
1. Can Moebooru handle as many images as possible like Danbooru's 3.33 Million images?
2. Can Moebooru handle  as many user in parallel as possible like Danbooru does currently?
3. What are the other performance differences between Moebooru and Danbooru?
4. What are the UX differences between Moebooru and Danbooru?
5. Does it come with IQDB, post/pool versioning, archives and recommendations?

**Comment by nanaya** [comment]
No idea. I don't do load test or comparison with other things. It doesn't come with iqdb, archives, and recommendations. It does have some kind of post and pool versioning. Please figure out the rest by yourself or ask somewhere else (or wait if there's anyone else wanting to respond here).

Also as it doesn't seem you're reporting any issue, I'm closing this.

**Comment by DonaldTsang** [comment]
@nanaya If it does not come with IQDB where does it come from for Konachan and Yandere?
