### ISSUE TITLE
Make moderate query user search automatically include held posts

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#114]
![image](https://user-images.githubusercontent.com/4130991/61165601-41834280-a4e8-11e9-9b20-3a0014b14d57.png)

When click this, it does a search of `user:xxx` only, so held posts won't be visible.

Probably better to automatically add `holds:all` search tag when clicking this button, or just change the way query search works, so held posts will always be displayed (just like when you're not doing the search).

**Comment by fireattack** [comment]
I assume commit 527ad29ff4bbbe3aab6fb28c34ae02010eef975b is about this, but currently click "mod" will still return a search without "holds:all" parameter.

(Or maybe it's just not applied to production yet?)

**Comment by nanaya** [comment]
Should be fixed now.

**Comment by fireattack** [comment]
Yeah, thanks!
