### ISSUE TITLE
Reply textarea broken in Chrome M77

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#117]
Normal:

![image](https://user-images.githubusercontent.com/4130991/63000316-7875ac80-be36-11e9-8d01-aaad8423e200.png)

Broken:

![image](https://user-images.githubusercontent.com/4130991/63000338-83c8d800-be36-11e9-8a78-0e01ddd7fdf3.png)

**Comment by fireattack** [comment]
Looks like a Chrome bug, reported to https://bugs.chromium.org/p/chromium/issues/detail?id=997052

**Comment by nanaya** [comment]
Seems fine now.
