### ISSUE TITLE
Frame by frame implementation

### ISSUE THREAD

**Issue by abckevinlee** [moebooru/moebooru#118]
I may have missed something entirely, so feel free to remove this post if its already present, but I wanted to suggest something that would allow for the video to play frame by frame, kind of like how on YouTube if you use the < and > keys, they go frame by frame. I've tried searching for it, but to no avail, and while the arrow keys do kind of work, I think it skips multiple frames, as opposed to being 1 frame at a time. This is a database for animation, and I'm assuming many people would make great use of this feature (if not already implemented). I am a bit of a newbie when it comes to  coding, but hopefully this isn't something too difficult to put in action.

**Comment by nanaya** [comment]
The one here doesn't actually have support for video. It's Sakugabooru specific feature and you'll better off requesting it over there. Or whatever site you visit which supports video upload.

If any of team member of such site is reading this, feel free to make pull request for that.

Closing this as this isn't relevant here (yet?).
