### ISSUE TITLE
Issue: Only text on page

### ISSUE THREAD

**Issue by Veshurik** [moebooru/moebooru#124]
I have a problem, only text appears on page and I can't browse site.

If I use VPN, it's ok, but not my usual Internet.
Provider support said "it's not our business".

My IP: 
 185.155.18.120

![Скриншот 16-10-2019 175400](https://user-images.githubusercontent.com/26744056/66936887-1f4d1380-f047-11e9-8ebb-403271342652.jpg)

**Comment by nanaya** [comment]
This isn't support forum for specific site. Please do it in the site itself.
