### ISSUE TITLE
Gemfile is beyond broken

### ISSUE THREAD

**Issue by ghost** [moebooru/moebooru#125]
Tried on Ubuntu Server 18.04 in Virtualbox.
nokogiri wouldn't install, the fix was to do this:

apt install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev

^ This is mentioned nowhere in the install guide.

Then, pg wouldn't install. Idk how to fix it. Now the entire thing is unable to be installed. Idk how people are doing that but I assume they're magic wizards sent from the heavens or something.

Can't you just add an install.sh script? It'd make people's lives 1000x easier.

**Comment by nanaya** [comment]
Maybe you should check the [requirement section](https://github.com/moebooru/moebooru#requirements). Some of the versions are a bit outdated but it's still more or less the same.
