### ISSUE TITLE
structure.sql error

### ISSUE THREAD

**Issue by Nao8617** [moebooru/moebooru#129]
Hi,

When I do a bundle exec rake db:reset I  get the following error : 
![Annotation 2020-02-16 032057](https://user-images.githubusercontent.com/40797221/74597691-8e715d80-5063-11ea-9a8f-7dff3c0bd1ca.png)
I am using debian 10 and postgresql 12.2. What did I do wrong ?

**Comment by Nao8617** [comment]
Finally commented the line and it works well.

**Comment by nanaya** [comment]
If you're wondering what's happened, check if you have

- multiple postgresql installed,
- the `psql` in your path is actually version 12,
- and the server is version 12 as well
  - it should say `psql (12.2)` instead of something like `psql (12.2, server 11.7)`
