### ISSUE TITLE
Display image with EXIF orientation properly

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#132]
Example: https://yande.re/post/show/632678

This image has EXIF orientation of `6` (`right top`, or `Rotate 90 CW`).
The image itself displays in correct orientation as it is rendered by the browser, but our rendered HTML gives it wrong size (W and H ratio should be flipped).

**Comment by nanaya** [comment]
Fixed in 8a82a1b (for future uploads).

**Comment by fireattack** [comment]
@nanaya I don't think it's a good idea. JPEG rotation (including `jpegtran`) can only handle image that are multiples of 8x8 (DCT size). Otherwise it will pad it with unwanted pixiels.

Raw:

![raw](https://user-images.githubusercontent.com/4130991/81190920-0887f300-8f7e-11ea-806b-5dd647730fbc.jpg)

```
jpegtran.exe -rotate 90 raw.jpg > output.jppg

```

![output](https://user-images.githubusercontent.com/4130991/81190984-1b9ac300-8f7e-11ea-968e-c082cd3ce50c.jpeg)

(See how the right side of the image is ruined by random pixels)

**Comment by nanaya** [comment]
huh, that's annoying. Adding "proper" support for displaying exif-rotated image will be pretty difficult.

I won't be fixing this anytime soon.

**Comment by fireattack** [comment]
Yeah probably just leave it as-is and don't convert it. At least the raw data is preserved, just a display issue.

**Comment by nanaya** [comment]
Should be properly fixed now. I don't even want to see word exif for next few months.
