### ISSUE TITLE
no css

### ISSUE THREAD

**Issue by Kille250** [moebooru/moebooru#14]
http://moebooru.org

it don't shown the css there. What i have doing wrong?

**Comment by edogawaconan** [comment]
> What i have doing wrong?

not running rake task of `assets:precompile`

**Comment by Kille250** [comment]
how do i run that? Sorry for the question.

**Comment by edogawaconan** [comment]
Check this page http://guides.rubyonrails.org/asset_pipeline.html#in-production

**Comment by Kille250** [comment]
i have run 
```
$ RAILS_ENV=production bin/rake assets:precompile
```
Two directorys are created but the filenames aren't right and one javascript file was created. I think i'm dumb. Sorry for stealing you'r time.

**Comment by edogawaconan** [comment]
restart unicorn/passenger/whatever you're using

**Comment by edogawaconan** [comment]
also this isn't really a bug so contact me through irc/email instead.

**Comment by Kille250** [comment]
have contacted you via e-mail.
