### ISSUE TITLE
"My Favorites" list does not work

### ISSUE THREAD

**Issue by AntiSephiroth** [moebooru/moebooru#143]
Hello. When I go to "My Favorites" list, only appears "Nobody here but us chickens!". The list of favorites does not show any image. Three years ago I already had a similar error:
[https://github.com/moebooru/moebooru/issues/73](url)

Can anyone help me with this again please? ^_^"
My Yande.re username: Антисфирот

**Comment by nanaya** [comment]
Should be fixed now (or whenever the server deploys the change).

**Comment by AntiSephiroth** [comment]
It's okay now. Thank you so much for helping out again :3
