### ISSUE TITLE
Login and Registration successful, but no logged in state

### ISSUE THREAD

**Issue by seanwestfall** [moebooru/moebooru#150]
It's pretty much the same as this issue [https://github.com/moebooru/moebooru/issues/99](https://github.com/moebooru/moebooru/issues/99), but even with `CONFIG["server_host"]` set correctly, I'm still getting the same problem.

From `development.log`
https://pastebin.com/d6uQbdK9

**Comment by nanaya** [comment]
Did you access it through same address as the server host config?

**Comment by seanwestfall** [comment]
yes, if you go through the log you can see it. As of this moment I haven't taken the server down either.

**Comment by nanaya** [comment]
in

https://github.com/moebooru/moebooru/blob/34d6cfc5bda4a3918d45a4c5efd463bb40d0976c/config/initializers/session_store.rb#L3

change `CONFIG["app_name"]` to `CONFIG["app_name"].parameterize`

I'll update that later.

**Comment by seanwestfall** [comment]
that worked @nanaya !
