### ISSUE TITLE
Mobile support for Sakugabooru

### ISSUE THREAD

**Issue by ImSorryYoureWelcome** [moebooru/moebooru#152]
Just wondering if anyone out there is working on a better mobile implementation of Sakugabooru. More people use Androids and iPhones than desktops these days. It could be extremely beneficial to the site to have built-in video cropping, trimming, audio stripping, and conversion. Or maybe just make an official app?

**Comment by shakealeg** [comment]
This repository is unrelated to Sakugabooru. The idea of cropping, trimming, etc could be interesting, but that probably isn't high priority. Making an official app is a stupid idea, it would slow down development by a bunch as this project seems to be mostly managed and programmed by one person.
