### ISSUE TITLE
 Sprockets::Rails::Helper::AssetNotPrecompiled in Static#index

### ISSUE THREAD

**Issue by ebrasca** [moebooru/moebooru#156]
Showing /home/ebrasca/moebooru/app/views/layouts/application.html.erb where line #30 raised: 

Trace of template inclusion: #<ActionView::Template app/views/layouts/bare.html.erb locals=[]>

Rails.root: /home/ebrasca/moebooru
Application Trace | Framework Trace | Full Trace
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:349:in `find_debug_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:230:in `block in lookup_debug_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:242:in `each'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:242:in `detect'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:242:in `resolve_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:229:in `lookup_debug_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:171:in `block in stylesheet_link_tag'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:170:in `map'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:170:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:30
actionview (6.1.2.1) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.2.1) lib/action_view/base.rb:247:in `_run'
actionview (6.1.2.1) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.2.1) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.2.1) lib/action_view/template.rb:152:in `render'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (6.1.2.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.1.2.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.1.2.1) lib/action_view/renderer/renderer.rb:22:in `render'
actionview (6.1.2.1) lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
actionview (6.1.2.1) lib/action_view/base.rb:273:in `in_rendering_context'
actionview (6.1.2.1) lib/action_view/helpers/rendering_helper.rb:34:in `render'
app/views/layouts/bare.html.erb:1
actionview (6.1.2.1) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.2.1) lib/action_view/base.rb:247:in `_run'
actionview (6.1.2.1) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.2.1) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.2.1) lib/action_view/template.rb:152:in `render'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:72:in `block in render_with_layout'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
actionview (6.1.2.1) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (6.1.2.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.1.2.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.1.2.1) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.1.2.1) lib/action_view/base.rb:273:in `in_rendering_context'
actionview (6.1.2.1) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.1.2.1) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.1.2.1) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.1.2.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.1.2.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.1.2.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.1.2.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.1.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
/usr/lib64/ruby/2.6.0/benchmark.rb:308:in `realtime'
activesupport (6.1.2.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.1.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (6.1.2.1) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
activerecord (6.1.2.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.1.2.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
actionpack (6.1.2.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (6.1.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.2.1) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.2.1) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
actiontext (6.1.2.1) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (6.1.2.1) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
activesupport (6.1.2.1) lib/active_support/callbacks.rb:126:in `instance_exec'
activesupport (6.1.2.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
activesupport (6.1.2.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
actionpack (6.1.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.2.1) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.2.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.2.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.2.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.2.1) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.2.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.2.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.2.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.2.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.2.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.2.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.2.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
newrelic_rpm (6.15.0) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
newrelic_rpm (6.15.0) lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activerecord (6.1.2.1) lib/active_record/migration.rb:601:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.1.2.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.2.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.2.1) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.2.1) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.2.1) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activesupport (6.1.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.2.1) lib/action_dispatch/middleware/static.rb:24:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-mini-profiler (2.3.1) lib/mini_profiler/profiler.rb:248:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.1.2.1) lib/rails/engine.rb:539:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/lint.rb:50:in `_call'
rack (2.2.3) lib/rack/lint.rb:38:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/show_exceptions.rb:23:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/common_logger.rb:38:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/chunked.rb:98:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/content_length.rb:17:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
unicorn (5.8.0) lib/unicorn/http_server.rb:634:in `process_client'
unicorn-worker-killer (0.4.4) lib/unicorn/worker_killer.rb:52:in `process_client'
unicorn-worker-killer (0.4.4) lib/unicorn/worker_killer.rb:92:in `process_client'
unicorn (5.8.0) lib/unicorn/http_server.rb:732:in `worker_loop'
unicorn (5.8.0) lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
unicorn (5.8.0) lib/unicorn/http_server.rb:144:in `start'
unicorn (5.8.0) bin/unicorn:128:in `<top (required)>'
/usr/bin/unicorn:23:in `load'
/usr/bin/unicorn:23:in `<main>'
Request

Parameters:

None

Toggle session dump

_csrf_token: "urlNpItWTWuqiZdDZJR4SvMxFSKZUtM6PqbvX3uFxB8="
session_id: "936d1271b6b2c9086520a1cb22e052a2"

Toggle env dump

HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.5"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "192.168.10.2"
SERVER_NAME: "192.168.10.144"
SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

None

**Comment by nanaya** [comment]
This isn't support forum. Either try searching first or make a better bug report if it's actually a bug.
