### ISSUE TITLE
Missing images during search (empty blacklist)

### ISSUE THREAD

**Issue by minirop** [moebooru/moebooru#165]
Hello,

I was looking for a picture and couldn't find it, so I used iqdb and did find the link to it: [https://yande.re/post/show/745972](https://yande.re/post/show/745972).
But if you click on the artist tag, this image doesn't appear in the list. Also, the count near the artist's name is 129 but there are only 72 images visible, so there might be more than one missing it seems.
It's not a blacklist problem since I tried with it empty, and it says "hidden posts 0". And from another browser, not logged in, same thing with just 1 hidden image (i.e. 71 visible) because rating explicit.

Regards.

**Comment by fireattack** [comment]
It says on top "This post has been temporarily held from the index by the poster."

See wiki there: https://yande.re/wiki/show?title=howto%3Ahold

**Comment by minirop** [comment]
oh. ok. thanks.
