### ISSUE TITLE
Vote API will leak other users' blacklist

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#170]
```
curl -d "user[name]={yourname}&user[password]={yourpass}&id=469991&score=2" -X POST "https://yande.re/post/vote.json"
```

Do this, it will output all the users that have been voted on this post, together with their blacklists.

**Comment by nanaya** [comment]
More like it's included in any user json data and not just that.

**Comment by nanaya** [comment]
Should be gone now.
