### ISSUE TITLE
How do you use /post/revert_tags.xml ?

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#172]
I tried to use it, but have no idea what is `history_id`. For example for [post 817023](https://yande.re/history?search=post%3A817023), I tried to put either the change id `3790450` or another id I found in the JS, `10735348`, none of them work. All I got is 404.

**Comment by nanaya** [comment]
That endpoint is kinda dead. The correct one is `/history/undo` with the change id 3... you found.

**Comment by fireattack** [comment]
Thanks, it works, but you actually have to use the second id (`10735348`) in this case.

Sometimes a rev id have multiple these ids, for example [`change:3778602`](https://yande.re/history?search=change%3A3778602&commit=Search) have `[ 10700695, 10700696 ]`.
