### ISSUE TITLE
Is it possible to get a random posts?

### ISSUE THREAD

**Issue by nonetrix** [moebooru/moebooru#177]
The issue:

In Danbooru https://danbooru.donmai.us/posts/random.json?tags=rating:safe works but in Moebooru this doesn't work, and the only places I could find documentation https://konachan.com/help/api and https://yande.re/help/api do not seem to mention anything about getting a random post

https://yande.re/post/random exists, but I can't sort by rating, and also it gives me the full URL not the image URL

Ways to implement this possibly if theirs not a way to do this:
- make https://yande.re/post/random.json do the same as https://yande.re/post/random but return JSON instead

**Comment by nanaya** [comment]
search with `order:random`

**Comment by nonetrix** [comment]
thanks
