### ISSUE TITLE
Can't view full size image or downloading them on Yande.re

### ISSUE THREAD

**Issue by NanashiAkira** [moebooru/moebooru#18]
I can see the image on the main page of Yande.re but when I click for looking at the full size all I see is this : http://puu.sh/gCsEt/cd2a9cce8e.png
and when I try downloading the image, I have a 503 error : http://puu.sh/gCsM2/3d0d80bd45.png
Is it from me or is it from the servor ? Please help me ! Thank you

**Comment by edogawaconan** [comment]
it means you're accessing the site too quickly. I've fixed the error message.
