### ISSUE TITLE
md5 mismatch on posts that shouldn't be happening

### ISSUE THREAD

**Issue by Fuuf7** [moebooru/moebooru#185]
A few days ago, I wrote a scraper that copies some posts from danbooru to post on a moebooru. Most of the posts went through ok, but around 800 of the 3500 failed due to an md5 mismatch. Some of them were expected due to being videos or pixiv ugoiras, but most of them were a complete mystery. The md5 of the image did not change when it was fetched from danbooru, so something must have gone wrong during the moebooru post. In case it was a network issue, I wrote a retry method, but certain posts seem to just always cause an md5 mismatch and I have no idea why. 

It is not a huge issue, since I can just disable the md5 check on upload, but I am completely lost on what was failing in the first place. It was weird to see so many error 420 in the log. It did not have anything to do with the bad_id or md5_mismatch tags on danbooru

Example post that always failed: https://danbooru.donmai.us/posts/603408
md5 in the program:
![image](https://user-images.githubusercontent.com/83101422/147223622-2d16672b-4dfa-4dcd-9199-447cbb938c2d.png)
manually checking the md5:
![image](https://user-images.githubusercontent.com/83101422/147223655-baed5842-c649-4c12-928b-886def98f5c6.png)

**Comment by fireattack** [comment]
If you meant that the post doesn't retrain its MD5 after posting to moebooru, that's because we strip metadata from the image.

In this very case, it has quite a few KB of XMP data that are stripped.
