### ISSUE TITLE
Unable to get posts with page id greater than 5000 from yande.re

### ISSUE THREAD

**Issue by MoooChaaa** [moebooru/moebooru#187]
For example, when I request **[/post?page=5001](https://yande.re/post?page=5001)**, it will return `can't go beyond requested page`.

I understand that this issue is not related to this repository. But I'd really want to know how to get older posts in other ways.

**Comment by fireattack** [comment]
https://yande.re/forum/show/33212

**Comment by nanaya** [comment]
Search based on post id instead `q=id:<500` etc
