### ISSUE TITLE
Post edit stays up even after saving changes

### ISSUE THREAD

**Issue by ThereIsNoBacon** [moebooru/moebooru#190]
No amount of reloading or jumping to other sections makes it disappear, and there appears to be no direct ways of stopping it either

**Comment by nanaya** [comment]
Not sure what you're talking about but the mode selection on the left sidebar doesn't revert back automatically.

**Comment by gohichiban** [comment]
> No amount of reloading or jumping to other sections makes it disappear, and there appears to be no direct ways of stopping it either

If you're talking about the comment section, just press the respond button that is next to edit.
