### ISSUE TITLE
Issues with Self-Hosting on Plesk with PhusionPassenger (Ubuntu 20.04)

### ISSUE THREAD

**Issue by HayateLaTech** [moebooru/moebooru#201]
Hewwo!
I currently try setting Moebooru up on my VServer (Ubuntu 20.04 LTS) that has Plesk installed.

Ruby: 3.1.2-p20
Postgresql: 14.5
NodeJS: 18.12.0

- Setting up psql with the moebooru user worked flawlessly, triggering the db commands throws no errors and the tables get created
- assets:precompile works without throwing any errors too
- the Ruby extension on Plesk shows no errors either

![image](https://user-images.githubusercontent.com/26610017/200005539-bda5be16-bfac-4b20-86d4-1126d3311b35.png)

The Problem I'm facing now is that whenever I want to open the website, it shows me a HTTP 403 Error because: (from apache logs)

> AH01276: Cannot serve directory /var/www/vhosts/website/moebooru/public/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm,index.shtml) found, and server-generated directory index forbidden by Options directive, referer: https://website/

.. and I'm not sure what to do ;w;

Do I need to set up some more environment variables?
Should I setup some apache / nginx specific configurations so that the webserver can find the index file?

Or should the precompile command generate those files in the /public folder?

**Comment by nanaya** [comment]
I don't have access to plesk so I don't think I can help you.

**Comment by HayateLaTech** [comment]
After lots of trial and error and basically re-installing plesk modules left and right and fixing plesk configuration files I now have a somehow coherent error message:

> You have already activated strscan 3.0.1, but your Gemfile requires strscan 3.0.4. Since strscan is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default gem. (Gem::LoadError)

I tried fixing that error with triggering `bundle update --bundler` and `gem install bundler` but it stays on the same version..

Would you know how to fix that error? >.< I feel like I'm super close to finally getting it to run x3

**Comment by HayateLaTech** [comment]
oki! I manually changed the version of strscan in the gemfile lock to 3.0.1 (which is hopefully alrighty) and it's working nyow :D
