### ISSUE TITLE
Incorrect post id in "child posts"

### ISSUE THREAD

**Issue by NightLancer** [moebooru/moebooru#215]
Site shows parent post instead of one[Explicit?...] post in the list of child posts on the corresponding page.

Steps to reproduce/Example:
- open post that has several child posts
https://yande.re/post/show/1064480
![зображення](https://user-images.githubusercontent.com/19971564/223929943-2662c321-d18c-479a-875e-dd01f24bdaa7.png)
All child ids listed correctly on art page, child ids: 
1064413, 1064483, 1064485, **_1068687_**
- click "child posts". Now site shows parent's post instead of one children's
https://yande.re/post?tags=parent%3A1064480
![зображення](https://user-images.githubusercontent.com/19971564/223930763-7627e932-9ed8-4b2a-a190-8c40b383f284.png)
"1064485", "1064483", "_**~~1064480~~**_", "1064413"

Same bug with other similar arts. The key similarity I noticed that every time it's explicit-rated art being bugged. But site already shows every art by default and there's no option to define R18+ display so it shouldn't be a key of problem.

**Comment by nanaya** [comment]
it's just whoever posted the thing decided to hold some of them. try using `holds:all` search option
