### ISSUE TITLE
not view image and full size image them on Yande.re

### ISSUE THREAD

**Issue by 01028296241** [moebooru/moebooru#22]
![1](https://cloud.githubusercontent.com/assets/12915343/8197642/a2bc3d38-14d5-11e5-88ef-3c0efdda9167.PNG)

 click Download larger version
![2](https://cloud.githubusercontent.com/assets/12915343/8197643/a2bdab5a-14d5-11e5-9685-8712d7cfe806.PNG)

I can't see the image
other site see image only rande.re can't see
help me Please

**Comment by nanaya1** [comment]
get a real browser.

(your browser doesn't support encryption used by image server. It's been changed recently because the one that's compatible with ancient browser uses too much cpu)
