### ISSUE TITLE
How to reliably find the post page from a direct link

### ISSUE THREAD

**Issue by notevenaperson** [moebooru/moebooru#229]
I'm trying to find the post page of links such as these:
https://www.sakugabooru.com/data/d7bc363f8f82de5c9aaf561c4bf4867a.webm

I expected this to work:
https://www.sakugabooru.com/post?tags=md5:d7bc363f8f82de5c9aaf561c4bf4867a

Searching the md5 from the filename finds the post most of the time, but rarely, there's a post I just can't find.

**Comment by fireattack** [comment]
1.  this is not a support forum for moebooru
2. the post you're looking for was deleted. Add "deleted:all" to find it: https://www.sakugabooru.com/post?tags=md5%3Ad7bc363f8f82de5c9aaf561c4bf4867a+deleted%3Aall+
