### ISSUE TITLE
Undoing multiple histories is totally broken now.

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#23]
https://yande.re/history?search=pool%3A3759

Check the history of this pool.

When I try to undo all the changes _after_ Hatsukoi's last one by selecting them and click "undo", the result is wrong: some changes by 支离殇夏 and tys didn't get reversed.

**Comment by fireattack** [comment]
I encountered similar problem in this pool: https://yande.re/history?search=pool%3A3211

But I can't reproduce it with a test pool https://yande.re/history?search=pool%3A3825 . I guess this bug needs different accounts involved.

**Comment by fireattack** [comment]
Ok it's not limited to pool. https://yande.re/history?search=post%3A326214

**Comment by nanaya** [comment]
I need more time to fix this

**Comment by fireattack** [comment]
No problem, take your time.

**Comment by fireattack** [comment]
This thing is more and more broken JFYI and it's quite annoying.

An example here: https://yande.re/history?search=post%3A273703

I tried to undo all three edits from user:wxf3168536 (which should result in"no change"), but it end up with a weird combination of them.

**Comment by nanaya** [comment]
I think I got it fixed.

**Comment by fireattack** [comment]
Yeah, it seems fixed. Thank you very much!

Will open a new ticket if it happens again.
