### ISSUE TITLE
Cannot post any new clips

### ISSUE THREAD

**Issue by Neyoteriker** [moebooru/moebooru#234]
Hi! When trying to post something (through upload tab on the bottom of the page) I always get kicked back to the login page (even when already logged in) and get an "access denied" message. When I try logging in again on that page the same message keeps appearing over and over. Also tried to post my problem in the forum, however the same problem appears when I try to send my formular. Is there anything I can do to fix this? Am I overlooking something? Thanks in advance!
<img width="1038" alt="Bildschirmfoto 2024-04-21 um 19 08 40" src="https://github.com/moebooru/moebooru/assets/75307928/aa02c00e-6e73-46ae-bb89-51e05ebbbfd7">

**Comment by nanaya** [comment]
please ask the site admin, not here.
