### ISSUE TITLE
[ISSUE] production not working

### ISSUE THREAD

**Issue by shakealeg** [moebooru/moebooru#241]
I can't seem to get production working for moebooru. development works 100% fine and I've been using it for now, but production doesn't.
When I boot the Ruby server in the production environment and try to access the website, all assets fail to load and checking browser console, the assets return a 404. The simple HTML loads fine, but not assets. I followed the same steps as development in terms of setting up and made sure to precompile the assets. I also made sure to run all the setup commands with RAILS_ENV exported.
Any idea what causes this? Unless someone can tell me what the issue could be, then I'm just going to stick to development.
Command: `RAILS_ENV=production bundle exec rails server -P "/var/run/moebooru.pid" -b "127.0.0.1" -p "9292" -e "production"`

**Comment by nanaya** [comment]
try enabling the serve static file option or use a reverse proxy
