### ISSUE TITLE
reCAPTCHA always ends up saying failed

### ISSUE THREAD

**Issue by Boombaby22** [moebooru/moebooru#242]
Trying to create an account for Konachan.com and no matter what browser, device, or method I use, I only get "Error: reCAPTCHA Failed." Try Again. 
I have never failed a captcha so many times before so I am coming to ask and see if there is ANY chance that it is an issue with the backend, or if I just suddenly can't see or hear properly anymore to keep failing these captcha's. (The spinning captcha to make my github account to ask this question worked fine so I am at a loss.) 
Any input or assistance on how I can get my account created would be great. Thank you.

**Comment by nanaya** [comment]
please ask the server admin.
