### ISSUE TITLE
i couldn't make an acc cuz of reCAPTCHA

### ISSUE THREAD

**Issue by blawhh** [moebooru/moebooru#243]
i"ve been trying to make an acc since idk a year or something and it keeps saying reCAPTCHA error or something plssssssss help ! ! !

**Comment by nanaya** [comment]
please ask the server admin.

**Comment by blawhh** [comment]
> please ask the server admin.

how can i ?! ! ! !

**Comment by blawhh** [comment]
![image](https://github.com/user-attachments/assets/aa97ff6f-5969-4c8a-8848-704f6ac5804a)
