### ISSUE TITLE
Captcha Error: Unable to Register Due to Failed Captcha

### ISSUE THREAD

**Issue by Axalyzed** [moebooru/moebooru#245]
Hello, when I try to register on the page, I get "error: captcha failed." I tried using different browsers and got the same result. I'm not sure if it's a bug. Can someone help me?

![Sin título](https://github.com/user-attachments/assets/93715c76-36e3-4202-9f10-dfda872169c9)

**Comment by nanaya** [comment]
Ask the website administrator.
