### ISSUE TITLE
Can't sign up for Konachan R18

### ISSUE THREAD

**Issue by Woehhcold** [moebooru/moebooru#247]
I can't sign up for new account for Konachan R18 website.I try to sign it many time but it keep saying that Captcha Invalid.Is this a bug or something? Also why the website page is so big on phone? Its like website for computer.How to change it to become small?

**Comment by Cknight70** [comment]
I was unable to sign up due to "invalid captcha" bug, even tried on another browser with no changes or extensions to default settings

> Also why the website page is so big on phone? 
You would be better off using a booru mobile app even if this does get improved.

**Comment by nanaya** [comment]
This isn't konachan support site.
