### ISSUE TITLE
I can't create an account.

### ISSUE THREAD

**Issue by iuri844** [moebooru/moebooru#248]
Since months ago I have not been able to create an account on the website, and always with the same problem. 
Every time I go to finish, it says 'CAPTCHA ERROR'.
![Captura de tela 2024-09-14 195947](https://github.com/user-attachments/assets/a6b9582e-f98d-48ed-a5d1-2b20ec4a6f35)

**Comment by nanaya** [comment]
Unless it's about your own site installation, please ask the site admin.
