### ISSUE TITLE
Moebooru API - Query Votes?

### ISSUE THREAD

**Issue by gcscaglia** [moebooru/moebooru#27]
The API has no method to query a post and know which users voted to a post, or at least know if the logged in user has voted for a post. There is a method to cast a vote, but no means to know the current vote of a user.

When actually successfully casting a vote, the response will list all votes for the post from all users. But doing so will destroy the previous vote without means of restore.

The only workarounds I can think of is querying the post API with queries such as `id:1 vote:1:user`, `id:1 vote:2:user`, etc, or creating a sentinel user and voting at random with that user to get the full vote list. But either is awful.

Is there any undocumented method to query this kind of info? Could a method be created for it?

**Comment by nanaya** [comment]
I'll add fav_string just like the one in danbooru.

**Comment by nanaya** [comment]
sorry, apparently it's already there for json - you just need to pass these parameters:
```
api_version: 2
include_votes: 1
```

**Comment by gcscaglia** [comment]
I see, I was using the XML api. I will try and let you know if it works. Thank you.
________________________________
De: Edho Arief<mailto:notifications@github.com>
Enviada em: ‎04/‎10/‎2015 12:38
Para: moebooru/moebooru<mailto:moebooru@noreply.github.com>
Cc: gcscaglia<mailto:guilherme_scaglia@hotmail.com>
Assunto: Re: [moebooru] Moebooru API - Query Votes? (#27)

sorry, apparently it's already there for json - you just need to pass these parameters:
```
api_version: 2
include_votes: 1
```

---

**Comment by gcscaglia** [comment]
Yes it works. Checklist to get it working:

* Use json-type responses, i.e `http://booru/post.json`
* Include login/password_hash parameters for authentication.
* Include `api_version=2` and `include_votes=1` parameters.

The response will contain the usual `"posts":[...]` array, and a additional `"votes":{"id":vote,...}` _object_.

Thanks again.

**Comment by nonetrix** [comment]
Where is API documentation?
