### ISSUE TITLE
"Toggle view" in pools is broken

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#31]
Currently if you are logged in you are stuck on one view mode and this link doesn't do anything (it should change to another view mode). Only if you didn't log in, it will use another one. It's hard to describe two view modes but you should be able to check easily in any pool like https://yande.re/pool/show/3904

**Comment by fireattack** [comment]
Another kinda irrelevant thing: iirc there was a "browse" link too which leads you to browse mode of that pool but it's gone now. Maybe I remembered it wrong though.

**Comment by nanaya** [comment]
Fixed in 57148ae
