### ISSUE TITLE
Search by date updated

### ISSUE THREAD

**Issue by bobobo1618** [moebooru/moebooru#40]
It'd be nice to have this to see what's new and happening. It seems you can do it by created but not by updated, so you can't see posts which have a new tag for example.

**Comment by nanaya** [comment]
> new 

try `order:id_desc`

> happening

try `order:change_desc`

**Comment by bobobo1618** [comment]
That works, thanks! Is there somewhere this is documented? I couldn't find it on the [cheat sheet](https://yande.re/help/cheatsheet).

**Comment by nanaya** [comment]
don't know if it's documented anywhere [but it's mostly implemented here](/moebooru/moebooru/blob/master/app/models/post/sql_methods.rb).

**Comment by fireattack** [comment]
A more up-to-date version is here: https://yande.re/wiki/show?title=cheat_sheet_extended

But still, I never heard of `order:change` or `order:change_desc` either (and it's not documented there too).

**Comment by bobobo1618** [comment]
Ah, I see. Change is a sequential number. I was expecting rails' updated_at to be in the schema somewhere.

**Comment by bobobo1618** [comment]
Wait, it is. Reopening this as searching by date updated is a little different to ordering by change. They're close but it'd be nice to have the date too.

**Comment by fireattack** [comment]
What date? You can use `date:2016-03-31..2016-04-01`

**Comment by bobobo1618** [comment]
In the schema, `updated_at`. `date` is `created_at`. It looks like there's no index on `updated_at` though. Also looks like `updated_at` isn't returned in the API. I guess `change` is preferred to `updated_at` at the moment?

**Comment by fireattack** [comment]
If I read it correctly, that `updated_at` is only used when ordering by `vote`? Maybe it just means “voting time”? Try search with `order:vote vote:3:fireattack`

**Comment by bobobo1618** [comment]
I think it's being used that way for purposes of search but it's not how ActiveRecord uses it. ActiveRecord will update `updated_at` when you make _any_ modification to a row (like add tags) unless you explicitly tell it to do otherwise.

**Comment by fireattack** [comment]
@bobobo1618 I believe you mean this? https://github.com/moebooru/moebooru/blob/3328334f41ad75242bf1d00b7b7719fd59f96447/db/migrate/20120830051636_add_updated_at_to_posts.rb

Is this one (or files in /migrate/) really in use though?

**Comment by bobobo1618** [comment]
Seemed to on my test instance.

**Comment by fireattack** [comment]
Sorry I was not clear, I mean where does the value of `updated_at` get updated?

**Comment by bobobo1618** [comment]
Oh, anytime you update the database. It's built into ActiveRecord (part of Rails), you won't see it in this codebase. There are meagre docs [here](http://api.rubyonrails.org/classes/ActiveRecord/Timestamp.html).

**Comment by nanaya** [comment]
Very outdated reply but change sequence should already cover the need (tag updates).
