### ISSUE TITLE
Pagination not showing in Post#index

### ISSUE THREAD

**Issue by 1v** [moebooru/moebooru#42]
I have 30 posts in DB and for my main `/post` page pagination is not showing. I assume, because of `Post.fast_count(tags)` return `0`

```
    begin
      count = Post.fast_count(tags)
    rescue => x
      respond_to_error("Error: #{x}", :action => "error")
      return
    end
```

So I changed it to just `count = Post.count` and it works.

**Comment by 1v** [comment]
Ended up with this:

```
    begin
      if tags
        count = Post.fast_count(tags)
      else
        count = Post.count
      end
    rescue => x
```

**Comment by 1v** [comment]
This cache is not updating:

```
      cache_version = Moebooru::CacheHelper.get_version
      key = { :post_count => tags, :v => cache_version }

      count = Rails.cache.fetch(key) do
        Post.count_by_sql(Post.generate_sql(tags, :count => true))
      end.to_i
```
[github.com](https://github.com/moebooru/moebooru/blob/72626fab8e9a0958de845b1d159576a44aeb4fd2/app/models/post/count_methods.rb#L6)
`cache_version` always `0`

**Comment by antonizoon** [comment]
I figured out that removing the `.to_i` restores the total and the pagination in post#index again!

Moebooru::CacheHelper.get_version:

```ruby
    def get_version(type = "post")
      Rails.cache.read("#{type}_version")
    end
```

However, the per page gallery tag list on the left column on /post#index still doesn't show up. But pagination was the most important feature for me.

**Comment by nanaya** [comment]
The default cache store (file_store) behaves slightly differently. Should be fixed now.

As for tag list on the left, default view only shows last one day uploaded posts's non-general tags. And cached for one hour.

**Comment by nanaya** [comment]
Fixed, I guess?
