### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by t-k-** [moebooru/moebooru#44]
if your repo is dependent on readline, most likely you have to license this project on GPL.

**Comment by nanaya** [comment]
Nothing in the app requires readline. It's just listed as convenient alternative for line editing in ruby console.

**Comment by t-k-** [comment]
OK, sounds like readline-devel may not be included in Requirements section.
Seeing license issue can prevent people participating your project, for thoese who really consider legal issue.
That is just my suggestion.
