### ISSUE TITLE
Open Graph meta img require absolute url

### ISSUE THREAD

**Issue by 1v** [moebooru/moebooru#51]
I have relative URLs setting enabled `CONFIG["url_base"] = '/'`
```erb
<%= tag :meta, :property => 'og:image', :content => sample_url %>
```
but `sample_url` must be absolute here.
https://github.com/moebooru/moebooru/blob/7ef1b18fbb67033f7d2d20458792fa91c479224a/app/views/post/_social_meta.html.erb#L8

**Comment by nanaya** [comment]
yes, and...?
