### ISSUE TITLE
When a post WAS in a pool, it will be still considered as in that pool when searching with "-pool:xxx"

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#52]
Example:

Search for `nagimaya -pool:4103`
https://yande.re/post?tags=nagiyama+-pool%3A4103+

It should show [post #198154](https://yande.re/post/show/198154) because it is NOT in [pool #4103;](https://yande.re/pool/show/4103). However it didn't show because it WAS in that pool: https://yande.re/history?search=pool%3A4103

**Comment by nanaya** [comment]
Should be fixed.
