### ISSUE TITLE
[Question] Why is tag subs limit is divided by 3?

### ISSUE THREAD

**Issue by Parziphal** [moebooru/moebooru#54]
There's this option in the config:

```ruby
# Max number of posts to cache
CONFIG["tag_subscription_post_limit"] = 200
```

But that limit is divided by 3 when processing subscriptions, [here](https://github.com/moebooru/moebooru/blob/master/app/models/tag_subscription.rb#L14) and [here](https://github.com/moebooru/moebooru/blob/master/app/models/tag_subscription.rb#L38).

What's the reason for doing so?

**Comment by nanaya** [comment]
`..._limit / 3` is per-tag limit, `..._limit` is per-subscription limit.

**Comment by Parziphal** [comment]
Thanks for replying... but I don't understand. Do you mean that I can have `x` posts in total, and each tag will fill up to `x / 3`? That would mean that with 3 tags I would reach the limit but that doesn't make much sense.

**Comment by nanaya** [comment]
How so?

**Comment by Parziphal** [comment]
I think I've missunderstood how tag subscriptions are supposed to work, but I understand now. Thank you~
