### ISSUE TITLE
Serving 0 Posts - count_by_sql

### ISSUE THREAD

**Issue by Flat** [moebooru/moebooru#55]
Serving posts number shows 0, after searching the code I don't see a definition for count_by_sql for Posts which may be why.

**Comment by nanaya** [comment]
it's part of activerecord. And it's showing correct count for me.

**Comment by Flat** [comment]
Anything I should check in the database? All images were uploaded using the API would that be an issue?
![2016-08-16-13 29 09](https://cloud.githubusercontent.com/assets/2048861/17709050/8dcab19a-63b5-11e6-9495-809e950f0322.png)
![2016-08-16-13 30 16](https://cloud.githubusercontent.com/assets/2048861/17709061/99ab4696-63b5-11e6-9909-ec69d62a05f7.png)
