### ISSUE TITLE
Url parameters are being stripped from first/next/prev/last links

### ISSUE THREAD

**Issue by Cyberbeing** [moebooru/moebooru#57]
Url parameters such as tags= and limit= are being stripped from first/next/prev/last links which results in them redirecting to pages on the main post index instead of the proper tag result pages.

For example when loading a url such as:
`post?page=2&tags=tag_name&limit=55`

The next page link used to be the next page relative to the current url:
`<link href="/post?page=3&amp;tags=tag_name&amp;limit=55" rel="next" title="Next Page" />`

Yet now it is stripping parameters and pointing to completely different page on the main index:
`<link href="/post?page=3" rel="next" title="Next Page" />`

I just noticed this undesired behavior on yande.re yesterday, which must coincide with a moebooru update. The regression appears to be caused by 793a6a7d755eacf85237731e9ba7429b9933e599 which I can only assume was done in error? Or was there some other reason why that change was needed?

**Comment by nanaya** [comment]
Just fixed in a7b1e5db0337d5f42d559ca846176edaca1e316d.
