### ISSUE TITLE
 app error: wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by mindcrimes** [moebooru/moebooru#63]
whenever i try to load a page i get this error in the log:
E, [2016-11-07T20:15:26.008561 #30544] ERROR -- : app error: wrong number of arguments (given 2, expected 1) (ArgumentError)
E, [2016-11-07T20:15:26.008686 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/raindrops-0.17.0/lib/raindrops/middleware/proxy.rb:30:in `respond_to?'
E, [2016-11-07T20:15:26.008771 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/body_proxy.rb:14:in `respond_to?'
E, [2016-11-07T20:15:26.008851 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:735:in `each'
E, [2016-11-07T20:15:26.008928 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/body_proxy.rb:36:in `each'
E, [2016-11-07T20:15:26.009004 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_response.rb:57:in `http_response_write'
E, [2016-11-07T20:15:26.009077 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:573:in `process_client'
E, [2016-11-07T20:15:26.009135 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:92:in `process_client'
E, [2016-11-07T20:15:26.009191 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/oob_gc.rb:71:in `process_client'
E, [2016-11-07T20:15:26.009246 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:658:in `worker_loop'
E, [2016-11-07T20:15:26.009301 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
E, [2016-11-07T20:15:26.009356 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:132:in `start'
E, [2016-11-07T20:15:26.009410 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
E, [2016-11-07T20:15:26.009464 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/bin/unicorn:23:in `load'
E, [2016-11-07T20:15:26.009516 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/bin/unicorn:23:in `<top (required)>'
E, [2016-11-07T20:15:26.009572 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
E, [2016-11-07T20:15:26.009627 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
E, [2016-11-07T20:15:26.009681 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
E, [2016-11-07T20:15:26.009736 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
E, [2016-11-07T20:15:26.009790 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
E, [2016-11-07T20:15:26.009844 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-11-07T20:15:26.009898 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
E, [2016-11-07T20:15:26.009956 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
E, [2016-11-07T20:15:26.010011 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
E, [2016-11-07T20:15:26.010066 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
E, [2016-11-07T20:15:26.010119 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
E, [2016-11-07T20:15:26.010173 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
E, [2016-11-07T20:15:26.010285 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
E, [2016-11-07T20:15:26.010345 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
E, [2016-11-07T20:15:26.010399 #30544] ERROR -- : /home/dugdig/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'

Running Debian 8 with postgre 9.4

**Comment by nanaya** [comment]
Thanks for notification. I haven't looked deeply but one of the middlewares caused it. As it's not used I removed it in ceffe824161f062df7d61fa0316adbbb7a323cba.

**Comment by mindcrimes** [comment]
no problem
