### ISSUE TITLE
[Suggestion] Add slugs to posts' url automatically

### ISSUE THREAD

**Issue by bloodev** [moebooru/moebooru#65]
Currently every booru's posts page automatically links to /postNumber/tags-and-more-tags-and-such, which is basically **/{id?}/{slug?}**. 
Can you please add this to moebooru 5.x ? moebooru 3.x has that.

I tested and I can add anything after the /postNumber/, so I wonder how come you didn't add already this functionality to the page with all posts?

I mean, whenever there is a listing of posts to link to /postNumber/the-posts-tags

**Comment by nanaya** [comment]
The generated url is too long.
