### ISSUE TITLE
[Suggestion] JSON format search responces.

### ISSUE THREAD

**Issue by AraHaan** [moebooru/moebooru#69]
I would like the ability to have search results being in json format for use with languages like python where people want to make something that RNG's the images a person wants to search from a particular tag only.

Other languages can benefit from it as well.

**Comment by nanaya** [comment]
Not sure what you're asking about. Is there anything wrong with `/post.json`?

**Comment by AraHaan** [comment]
``http://xbooru.com/post.json?page=dapi&s=post&q=index&tags=`` seems to not exist. However ``http://xbooru.com/index.php?page=dapi&s=post&q=index&tags=`` Works.

Also just so you guys know ``http://drunkenpumken.booru.org/index.php?page=dapi&s=post&q=index&tags=`` just redirects to ``drunkenpumken.booru.org//``and does not do exactly what I want and list the posts available for tags.

I am thinking maybe there should be something like:

``
http://xbooru.com/index.php?page=dapi&s=post&q=index&format=json&tags=`` and have the ``format`` thing be optional for things like json. It would be nice too.

**Comment by nanaya** [comment]
...that's not even moebooru.

**Comment by AraHaan** [comment]
Hmm odd the site is acting just like how ``drunkenpumken`` does.

**Comment by fireattack** [comment]
None of them is moebooru. moe.booru.org and drunkenpumken are running Gelbooru.
