### ISSUE TITLE
Some urls point to the server IP

### ISSUE THREAD

**Issue by bloodev** [moebooru/moebooru#71]
I wasn't getting any pages indexed and when I looked in to the page source it was showing an IP instead of domain name, the IP being that of CloudFlair thus ofc. nothing would get indexed.

The places that I have noticed are:
```
<link rel="canonical"
<meta property="og:url"
<meta property="og:image" 
<link rel="image_src"
<link rel="alternate" type="application/atom+xml" title="ATOM"
```
In all five the IP is used, both if I surf over the domain name or the IP address of the web server.

I'm assuming that the route is not correctly generated and/or not picking CONFIG["server_host"] while in other places it picks it up.

PS: offtopic but how do I disable the preview image with text "this image is explicit, click to visit" ? I don't care about this warning - i want people to view the actual image preview when they link the website.

**Comment by nanaya** [comment]
I don't remember why but you need to pass `Host` and other common proxy headers properly. Or update the `ApplicationHelper`'s `with_host` method.

As for image preview, you need to change `app/views/post/_social_meta.html.erb` and `app/views/shared/twitter_card/_gallery.html.erb`.

**Comment by bloodev** [comment]
Do you happen to have the Host config? I assume I need to pass them in nginx?
I already have all CF proxy IPs in nginx as well as
```
        location @app {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          # Fix the "It appears that your reverse proxy set up is broken" error.
          proxy_pass http://127.0.0.1:9292;
          proxy_read_timeout 90;
          proxy_redirect http://127.0.0.1:9292 http://$server_name;
        }
```

Shouldn't this be enough? I don't quite get why it shows the domain name everywhere else but just for those five it shows the IP, any clue?

I guess I should change `"#{request.protocol}#{request.host_with_port}#{url}"` to `"#{request.protocol}mydomainname.com#{url}"` ?

**Comment by nanaya** [comment]
Somewhere in your proxy chain the header got removed? Also the atom link doesn't actually use `with_host` method so it'll only fix part of your problem.

**Comment by bloodev** [comment]
Well I changed `real_ip_header CF-Connecting-IP;` to `real_ip_header X-Forwarded-For;` but there's no difference.

Here's my nginx config file: http://puu.sh/t8Lvo/360ecadefb.txt

Any suggestion would be highly appreciated.
Otherwise I'll need to delete and manually write my domain name instead in those places (do tell me where to do it though)

Side question: since I'm new to RoR is there a way to update a page and see the changes (like the explicit warning image thing) without restarting each time the unicorn server?

**Comment by nanaya** [comment]
how are you running the unicorn server

**Comment by nanaya** [comment]
also I believe you've restarted/reloaded nginx after updating the confing.

**Comment by nanaya** [comment]
and god this isn't even supposed to be a support channel. Just continue replying but I may or may not respond anymore. I also need to do other things.

**Comment by bloodev** [comment]
Well I did restarted nginx after each change but I still see the IPs.
Here's how I run the unicorn:
`MB_MEMCACHED_SERVERS='127.0.0.1:11211' RAILS_ENV=production bundle exec unicorn -p 9292 -D`

**Comment by nanaya** [comment]
try accessing your web server directly without cloudflare and see if it still returns the ip.

**Comment by bloodev** [comment]
I tried, yes - it does still show IPs only for those 5 cases - everything else is again domain name.

**Comment by nanaya** [comment]
I don't know then. It works here for me. (as for why only those places, it's because the other places use relative url or the CONFIG variable)

**Comment by bloodev** [comment]
Any particular reason why those 5 ones are not using the CONFIG var?

Btw changing with_host(url) to anything in application_helper.rb doesn't do a thing.
I tried it with only test.com, no change

**Comment by nanaya** [comment]
as for `with_host`, I don't remember why. The atom link uses rails builtin function.

You need to restart the server after changing it.

**Comment by bloodev** [comment]
well I give up, I set CloudFlair to be 'under development mode' so I can see the changes, I changed the application_helper.rb to
```
  def with_host(url)
    return "google.com"
  end
```
I restarted unicorn. Absolutely no changes.

**Comment by bloodev** [comment]
After checking http://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html i switched all to have `:host=>'mysite.com'` specially instead of `:only_path => false`. 

This fixes my issue. Since atom is cached, I guess it will take some time to update.

**Comment by bloodev** [comment]
The only two I couldn't figured out where to edit were the atom generator (half of the entries have IP and the other correct domain name) and on post index page the XML link points to an IP (the atom one is correct)
