### ISSUE TITLE
"My Favorites" list does not work

### ISSUE THREAD

**Issue by AntiSephiroth** [moebooru/moebooru#73]
Hello. I have a problem: in my Yande.re account 495 pictures marked as favorite. But whenever I go to "My Favorites" list, only appears "Nobody here but us chickens!"
At the same time, "My Profile" displays the first 6 favorite images. When I click on the image, "Options" indicates that the image is credited to "My Favorites" list. But the list of favorites, as I said, does not show any image.

It started just 2-3 days ago. Previously, it was all good. Can anyone help with this?
My Yande.re username: Антисфирот

**Comment by nanaya** [comment]
The encoding was kind of broken. Fixed, thanks.

**Comment by AntiSephiroth** [comment]
Hello. Three years later, I got the same error: when i go to "My Favorites" list, only appears "Nobody here but us chickens!". The list of favorites does not show any image. 

Can anyone help me with this again? ^_^"
My Yande.re username: Антисфирот
