### ISSUE TITLE
how about https?

### ISSUE THREAD

**Issue by mad025** [moebooru/moebooru#75]
Hi everyone. I just signed up and I realise that there is no https on the site. I cannot think about a website i used recently that doesn't provide encryption, so i guess i think it should be everywhere. i'm not really ok with people seeing what i do, hence the question: is it possible to add https? Thank you very much. I just discovered it today so cannot really talk a lot about it but so far i like it really much :)

**Comment by nanaya** [comment]
Try visiting the correct site.
