### ISSUE TITLE
Reset password doesn't send mail?

### ISSUE THREAD

**Issue by ghost** [moebooru/moebooru#77]
I have set up a test moebooru server and i tried testing the email by reseting my own admin account and now i cannot log in or nor get the password in email? How do i setup the mail? Where are the files for it?

**Comment by nanaya** [comment]
check the log. Or read this http://guides.rubyonrails.org/action_mailer_basics.html

**Comment by Hitogami** [comment]
@nanaya  Thanks for the tips, i don't see anything in log files (development.log) about password only database select info.

**Comment by nanaya** [comment]
Check your configuration which mailer you use and check the respective log.

Removing user only available through rails console.

**Comment by Hitogami** [comment]
@nanaya Can you give me the command for deleting the user from rails c console?

**Comment by nanaya** [comment]
`User.find(id).destroy`. May or may not work. Also this isn't support area.
