### ISSUE TITLE
Script unresponsive in browse mode

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#79]
Users have reported this problem recently several times in the forum, and I personally encountered it several times today.

![image](https://cloud.githubusercontent.com/assets/4130991/24584919/9219f4b2-1743-11e7-9a14-11a308ac6e75.png)

It almost always happens after I scroll enough pictures. I don't think the keywords matter, as long as the query returns enough results. I was searching for `date:2017-01-01.. order:score -vote:fireattack -photoshop ` for what it's worth.

**Comment by nanaya** [comment]
Fixed. Kind of.
