### ISSUE TITLE
Ignore protocol in URL for "find artist" feature

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#81]
Recently, pixiv enabled HTTPS by default. Therefore, if you copy the URL of artist's pixiv homepage (i.e. `https://www.pixiv.net/member.php?id=113939`) and use "find artist" in any page (such as https://yande.re/post/upload), it doesn't show any result despite the artist is already in the database: https://yande.re/wiki/show?title=gin_%28oyoyo%29

That's because that most of URLs in the database, particularly pixiv ones, are using HTTP as protocol. 

The matching algorithm should ignore the protocol when looking for artist. Danbooru seems not to have this problem (try at http://danbooru.donmai.us/uploads/new).

**Comment by nanaya** [comment]
I think this has been fixed.
