### ISSUE TITLE
Posts API - Tag types

### ISSUE THREAD

**Issue by gcscaglia** [moebooru/moebooru#83]
The current API, specifically the `/post.json` endpoint, does not seems to provide any means to know the type of the tags in a post. Its not always possible to determine this by the `/tags.json` endpoint since multiple tags can have the same name but different types.

Is there any undocumented means to reliably determine the type of a tag from a post, preferably without N+1 queries?

If not, I propose an option to have that info on the `/post.json` endpoint. Perhaps a second `tag_types` array where each item is the type of the corresponding tag in the `tags` array? This is ugly but keeps the API backwards-compatible. Any other means in this same endpoint are fine too.

**Comment by nanaya** [comment]
There's `tag/summary.json`.

**Comment by gcscaglia** [comment]
I've peeked at it just now.

Since I don't know what parameters it takes, I've just called it without any and received what seems to be all  tags of the booru, preceded by their types (numeric).

Does this endpoint supports filtering by post? If so, it solves my problem completely. If not, the problem of tags with same name still persists.

**Comment by nanaya** [comment]
One tag can only have one type.

**Comment by gcscaglia** [comment]
Sorry, I was probably mixing up moebooru with danbooru, where you can have `artist:bow` and `general:bow` at the same time.

I'm indeed unable to find two tags with the same name but different types in any moebooru site; they usually do it like `general:bow` and `artist:bow_(artist)`.

Thank you, `tag/summary.json` will do it nicely.
