### ISSUE TITLE
“Find artist” by URL doesn't work well for twitter (possible cache problem?)

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#84]
For example, search for "https://twitter.com/ryohka_jp" doesn't return [ryohka](https://yande.re/wiki/show?title=ryohka).

However, if you edit the artist db once and save (I didn't do it for ryohka but I tested other entries), it will be searchable. 

So far I only encounter this problem with Twitter links (try this also: https://twitter.com/rin_royal )

**Comment by nanaya** [comment]
Just need some refresh due to https update.
