### ISSUE TITLE
Why delete upscaled game CG?even I try best to make it looks more lovely?

### ISSUE THREAD

**Issue by TigerIIAusfB** [moebooru/moebooru#85]
I think my process is pretty effective in resampling and upscaling,as you know most of game CG is at     source resolution 1280x720,however mainstream monitors are overtoping this resolution,so it`s appropriate this can make game CGs more accord with mainstream display devices as wallpapers.maybe you will say most people can do upscaling by themselves,maybe I am not the best one to do this,but I think there are many people who want some suitable game CGs as wallpaper can not do an effective upscaling for their monitors.At last in yande.re my name is EushullyChan,hope you will give me a reasonable answer.
Thank you!

**Comment by nanaya** [comment]
This isn't place to discuss this. Please do it in forum. Also it might be better to just share your awesome upscaling method instead of just uploading whatever you want.

**Comment by TigerIIAusfB** [comment]
you are right,to teach one how to fish rather than just giving one a fish,however my upscaling method is not so easy to achieve...maybe I should make a executable program for everyone someday.
Thanks for answer my question！
