### ISSUE TITLE
denying uploads from non admins?

### ISSUE THREAD

**Issue by Rhodesia** [moebooru/moebooru#87]
Is it possible to shut off uploads temporarily for non admins?(in the case of a flood, spam, etc)

**Comment by euank** [comment]
You could disable uploads by blocking the requests via nginx or whatever you front it with.

You could set `CONFIG["member_post_limit"] = 0` (or just low). You could set `CONFIG["enable_signups"] = false` and delete any flooding/spaming users. The whole approved/unapproved/post limit/starting level system is there partially for this sort of thing.
