### ISSUE TITLE
Why certain post will not be shown as cover even it has lowest page number?

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#88]
Case in point: [this post](https://yande.re/post/show/402705) in [this pool](https://yande.re/pool/show/4585) or  [this pool](https://yande.re/pool/show/4581) (check the hover thumbs in https://yande.re/pool)

**Comment by nanaya** [comment]
Because the post isn't shown in index..

**Comment by fireattack** [comment]
Ah, thanks.
