### ISSUE TITLE
Demo site on README.md does not work

### ISSUE THREAD

**Issue by Luk3M** [moebooru/moebooru#92]
It should be considered to remove or fix the demo site link (http://moe.dev.myconan.net/) on the README.md, because it is currently not working.

Maybe change for pictures of the software running?

**Comment by AriinPHD** [comment]
Yeah the website still doesn't work due to some sort of hostname pinning. Certificate hostname doesn't match the website hostname... Please fix; also upload screenshots to the readme - and a proper install-guide please.

**Comment by nanaya** [comment]
I removed it for now. There are a lot of stuff needed to be done, I don't have that much time, and proper install guide is at the bottom of my todo list.
