### ISSUE TITLE
public/data/avatars folder missing

### ISSUE THREAD

**Issue by RyoshiKayo** [moebooru/moebooru#94]
From the looks of it, `public/data/avatars` is missing, and you have to manually make the folder.

Error:
```
No such file or directory @ rb_file_s_rename - (/<snip>/public/data/309407618.avatar.jpg, /<snip>/public/data/avatars/1.jpg)
```

Application Stack Trace:
```
app/models/user.rb:532:in `set_avatar'
app/controllers/user_controller.rb:358:in `set_avatar'
```

If you need the framework and/or full trace I have those if you need.

**Comment by nanaya** [comment]
yes this is known.

**Comment by nanaya** [comment]
Fixed.
