### ISSUE TITLE
Keep showing "You are not logged in."

### ISSUE THREAD

**Issue by Minedient** [moebooru/moebooru#99]
I tried to install moebooru on a raspberry pi. I set everything up and start the server using "bundle exec unicorn" and browse the site using my browser.

I register an account and start uploading some photos in the server. But when I try to log in, it keep showing "You are not logged in." even i type the correct name and password. No error shown during the process of creating account and login. Can someone help me?

Development log if needed:
[https://pastebin.com/vv3DVD1L](https://pastebin.com/vv3DVD1L)

**Comment by nanaya** [comment]
Open `app/controllers/application_controller.rb`, find `def set_current_user`, add following line after it:

```
logger.debug "origin: #{request.origin.inspect } / base_url: #{request.base_url.inspect}"
```

Try to login and post the log again.

**Comment by Minedient** [comment]
Sorry for late reply. Here is the log after i add that code:

Development log:
[https://pastebin.com/C465RC69](https://pastebin.com/C465RC69)

**Comment by nanaya** [comment]
Whoops that was a rather pointless check. Do you have `CONFIG['server_host']` set correctly? It must match the domain/ip used to access the site.

**Comment by Minedient** [comment]
Seems I set the wrong ip for my CONFIG['server_host']. 

After I correct the ip, I can login now.

Thanks for helping, this problem has bothered me for quite a few days.
